export const MOUNTAINS = [
  "Monte Rosa",
  "Dom",
  "Lyskamm",
  "Weisshorn",
  "Matterhorn",
  "Dent Blanche",
  "Grand Combin",
  "Finsteraarhorn",
  "Zinalrothorn",
  "Alphubel",
  "Rimpfischhorn",
  "Aletschhorn",
  "Strahlhorn",
  "Dent d'Hérens",
  "Breithorn",
  "Jungfrau",
  "Mönch",
  "Schreckhorn",
  "Ober Gabelhorn",
  "Piz Bernina",
  "Fiescherhorn",
  "Grünhorn",
  "Weissmies",
  "Lagginhorn",
  "Piz Zupò",
  "Gletscherhorn",
  "Eiger",
  "Grand Cornier",
  "Piz Roseg",
  "Bietschhorn",
  "Trugberg",
  "Gross Wannenhorn",
  "Aiguille d'Argentière",
  "Ruinette",
  "Bouquetins",
  "Tour Noir",
  "Nesthorn",
  "Mont Dolent",
  "Schinhorn",
  "Pointe de Zinal",
  "Breithorn",
  "Piz Morteratsch",
  "Mont Vélan",
  "Evêque",
  "Combin de Corbassière",
  "La Singla",
  "Wetterhörner",
  "Le Pleureur",
  "Balmhorn",
  "Dent de Perroc",
  "Blüemlisalp",
  "Portjengrat",
  "Aiguilles Rouges d'Arolla",
  "Doldenhorn",
  "Dammastock",
  "Tödi",
  "Les Diablons",
  "Piz Glüschaint",
  "Mont Brulé",
  "Tschingelhorn",
  "Aouille Tseuque",
  "Monte Leone",
  "Mont Gelé",
  "Sustenhorn",
  "Sonnighorn",
  "Piz Corvatsch",
  "Rinderhorn",
  "Wasenhorn",
  "Piz Tremoggia",
  "Gspaltenhorn",
  "Stellihorn",
  "Bifertenstock",
  "Piz Kesch",
  "Rot Stock",
  "Piz Linard",
  "Rheinwaldhorn",
  "Fluchthorn",
  "Piz Calderas",
  "Piz Platta",
  "Diechterhorn",
  "Piz Julier",
  "Güferhorn",
  "Cima di Castello",
  "Blinnenhorn",
  "Pizzo Cengalo",
  "Egginer",
  "Piz Fora",
  "Piz Ela",
  "Mont Fort",
  "Oberalpstock",
  "Piz Buin",
  "Piz Paradisin",
  "Verstanclahorn",
  "Gross Schärhorn",
  "Muttler",
  "Hockenhorn",
  "Ritzlihorn",
  "Piz Fliana",
  "Pizzo Tambo",
  "Basòdino",
];
