export const MOUNTAINS = [
  "Monte Rosa (Dufourspitze)",
  "Dom",
  "Lyskamm",
  "Weisshorn",
  "Matterhorn",
  "Dent Blanche",
  "Grand Combin",
  "Finsteraarhorn",
  "Zinalrothorn",
  "Alphubel",
  "Rimpfischhorn",
  "Aletschhorn",
  "Strahlhorn",
  "Dent d'Hérens",
  "Breithorn",
  "Jungfrau",
  "Mönch",
  "Schreckhorn",
  "Ober Gabelhorn",
  "Piz Bernina",
  "Gross Fiescherhorn",
  "Gross Grünhorn",
  "Weissmies",
  "Lagginhorn",
  "Piz Zupò",
  "Gletscherhorn",
  "Eiger",
  "Grand Cornier",
  "Piz Roseg",
  "Bietschhorn",
  "Trugberg",
  "Gross Wannenhorn",
  "Aiguille d'Argentière",
  "Ruinette",
  "Bouquetins",
  "Tour Noir",
  "Nesthorn",
  "Mont Dolent",
  "Schinhorn",
  "Pointe de Zinal",
  "Breithorn (Lauterbrunnen)",
  "Piz Morteratsch",
  "Mont Vélan",
  "Evêque",
  "Combin de Corbassière",
  "La Singla",
  "Wetterhörner (Mittelhorn)",
  "Le Pleureur",
  "Balmhorn",
  "Dent de Perroc",
  "Blüemlisalp(horn)",
  "Portjengrat (Pizzo d'Andolla)",
  "Aiguilles Rouges d'Arolla",
  "Doldenhorn",
  "Dammastock",
  "Tödi (Piz Russein)",
  "Les Diablons",
  "Piz Glüschaint",
  "Mont Brulé",
  "Tschingelhorn",
  "Aouille Tseuque",
  "Monte Leone",
  "Mont Gelé",
  "Sustenhorn",
  "Sonnighorn/Pizzo Bottarello",
  "Piz Corvatsch",
  "Rinderhorn",
  "Wasenhorn",
  "Piz Tremoggia",
  "Gspaltenhorn",
  "Stellihorn",
  "Bifertenstock/Piz Durschin",
  "Piz Kesch/Piz d'Es-Cha",
  "Fleckistock/Rot Stock",
  "Piz Linard",
  "Rheinwaldhorn",
  "Fluchthorn",
  "Piz Calderas",
  "Piz Platta",
  "Diechterhorn",
  "Piz Julier/Piz Güglia",
  "Güferhorn",
  "Cima di Castello",
  "Blinnenhorn/Corno Cieco",
  "Pizzo Cengalo",
  "Egginer",
  "Piz Fora",
  "Piz Ela",
  "Mont Fort",
  "Oberalpstock/Piz Tgietschen",
  "Piz Buin",
  "Piz Paradisin",
  "Verstanclahorn",
  "Gross Schärhorn",
  "Muttler",
  "Hockenhorn",
  "Ritzlihorn",
  "Piz Fliana",
  "Pizzo Tambo/Tambohorn",
  "Basòdino",
];
